export default {
    holochainConnected: false,
    postsRead: {},
    commentsRead: {},
    commentsByAddress: {},
    votes: {},
    postTags: {},
    karmaMap: {},
    myVotes: {},
    voteJustCast: null,
    callZome: null,
    postJustCreated: null,
    commentJustCreatedTarget: null,
    commentJustCreated: null,
    errors: [],
    usernames: {},
};